ARDUINO_DIR  = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr

TARGET       = nrftesting
#ARDUINO_LIBS = Ethernet Ethernet/utility SPI
ARDUINO_LIBS = RF24 SPI

#BOARD_TAG    = atmega328
#ARDUINO_PORT = /dev/ttyUSB0
BOARD_TAG    = leonardo
ARDUINO_PORT = /dev/ttyACM3

include /usr/share/arduino/Arduino.mk

