ARDUINO_DIR  = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino

TARGET       = CLItest
#ARDUINO_LIBS = Ethernet Ethernet/utility SPI
ARDUINO_LIBS = IRremote RemoteSwitch LiquidCrystal Button RF24 SPI

BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB0
#BOARD_TAG    = leonardo
#ARDUINO_PORT = /dev/ttyACM3

include /usr/share/arduino/Arduino.mk

